In [2]:
import torch
import numpy

In [19]:
numpy.array([1,2,3]).shape

(3,)

In [4]:
dd= [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [10]:
t=torch.tensor(dd)

In [11]:
t.shape

torch.Size([3, 3])

In [15]:
t.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [14]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
t=torch.Tensor()

In [21]:
type(t)

torch.Tensor

In [22]:
print(t.dtype)#tyoe of data in tensor/ same type
print (t.device)#device where the computation will be performed
print (t.layout)#

torch.float32
cpu
torch.strided


In [23]:
# 4 primary ways to crate a tensor

In [24]:
data=numpy.array([1,2,3])

In [26]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [27]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#creating tensors without any data

In [33]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [35]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [4]:
dat=numpy.array(
[[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]])

In [5]:
t=torch.tensor(dat)

In [7]:
t.size()

torch.Size([4, 4])

In [9]:
t.shape

torch.Size([4, 4])

In [10]:
len(t.shape)

2

In [15]:
torch.tensor(t.shape).prod()

tensor(16)

In [16]:
torch.tensor(t.shape)

tensor([4, 4])

In [19]:
t.numel()

16

In [20]:
def flatten(t):
    t=t.reshape(1,-1)
    t.squeeze()
    return t

In [21]:
flatten(t)

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]], dtype=torch.int32)

In [23]:
t

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=torch.int32)

In [24]:
t.reshape([1,16])

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]], dtype=torch.int32)

In [25]:
t

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=torch.int32)

In [26]:
t+2

tensor([[3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]], dtype=torch.int32)

In [28]:
t*2#broaddcating

tensor([[2, 4, 6, 8],
        [2, 4, 6, 8],
        [2, 4, 6, 8],
        [2, 4, 6, 8]], dtype=torch.int32)

In [29]:
t>2

tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]])

In [ ]:
#creating a 3x3 rank 2 tensor

In [30]:
ts=torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [31]:
ts

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])